macros:
    - &linux
      language: c
      os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
              packages:
                  - ninja-build
      install:
          - source ~/virtualenv/python3.6/bin/activate
          - pip install meson
      script:
          - meson build $MESON_OPTS
          - ninja -C build $NINJA_TARGET

matrix:
    include:
        - <<: *linux
          env:
              - MESON_OPTS=-Djit=true
              - NINJA_TARGET=test
        - <<: *linux
          env:
              - MESON_OPTS=-Djit=false
              - NINJA_TARGET=
        - language: objective-c
          osx_image: xcode10.1
          install:
              - pip3 install meson==0.49.2
          addons:
              homebrew:
                  packages:
                      - ninja
                      - llvm
                      - yarn
                  update: true
          script:
              - xcodebuild -project iSH.xcodeproj -scheme iSH -sdk iphoneos CODE_SIGNING_ALLOWED=NO
    exclude:
        - language: objective-c
          env: MESON_OPTS=-Djit=false
